### ISSUE TITLE
docker plugin not working with docker 1.12.0-rc3

### ISSUE THREAD

**Issue by Nomon** [ClusterHQ/flocker#2854]
There is a new field passed to the docker plugin called 'ID':
https://github.com/docker/docker/pull/21015

The plugin (flocker 1.13.0) fails to mount the volume with the following error:
```
{"exception": "exceptions.TypeError", 
     "reason": "volumedriver_mount() got an unexpected keyword argument 'ID'",
     "timestamp": 1467628063.957701, 
     "traceback": "
    Traceback: <type 'exceptions.TypeError'>: volumedriver_mount() got an unexpected keyword argument 'ID'
      /opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
      /opt/flocker/local/lib/python2.7/site-packages/flocker/restapi/_infrastructure.py:264:loadAndDispatch 
      /opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred 
      /opt/flocker/local/lib/python2.7/site-packages/flocker/dockerplugin/_api.py:118:wrapped
     --- <exception caught here> ---  
     /opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred",
  "message_type": "eliot:traceback",
  "task_uuid": "6d68e5a3-1ef3-44e1-a477-e1cac6d76da2",
  "task_level": [3
}
```

**Comment by wallnerryan** [comment]
@Nomon thanks for reporting this, I was away on some time off but will be digging into 1.12 and making sure things work correctly and making needed changes, will update this issue as we go along

**Comment by wallrj** [comment]
Looks like 1.12 was released last week and all our Flocker Docker plugin tests are now broken :-(
 * http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/view/master/job/master/view/cron/job/_run_acceptance_on_GCE_Ubuntu_Xenial_with_GCE/7/#showFailuresLink

@wallnerryan Thanks for creating the Jira issue. 
Let me know if you want me to review / help with anything
 * https://clusterhq.atlassian.net/browse/FLOC-4480

**Comment by wallnerryan** [comment]
should be fixed now that https://github.com/ClusterHQ/flocker/pull/2880 is merged. Next release will/should include this.
